//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Registros_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public Vendedor()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int CodVendedor { get; set; }
        public string NombreCompleto { get; set; }
    
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
