//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Alumnos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int CodMatricula { get; set; }
        public int CodAlumno { get; set; }
        public int ValorMatricula { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
